version: "3"
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: nestjssample
    ports:
      - 15432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
